import {
  Boxes,
  Cable,
  CheckCircle2,
  Cloud,
  Globe,
  LayoutDashboard,
  LifeBuoy,
  Layers,
  MessageSquare,
  PenTool,
  Shield,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Target,
  Users,
  Workflow,
} from 'lucide-react'

export const SERVICE_ICONS = {
  boxes: Boxes,
  layoutDashboard: LayoutDashboard,
  globe: Globe,
  smartphone: Smartphone,
  sparkles: Sparkles,
  workflow: Workflow,
  penTool: PenTool,
  cloud: Cloud,
  cable: Cable,
  users: Users,
  target: Target,
  shield: Shield,
  messageSquare: MessageSquare,
  sliders: SlidersHorizontal,
  layers: Layers,
  checkCircle: CheckCircle2,
  lifeBuoy: LifeBuoy,
}
