export const homePartners = {
  eyebrow: '( Clients & Partners )',
  title: 'Brands and product teams we engineer with',
  support:
    'Selected partners from our published case studies — products we’ve helped design, build, and scale.',
  cta: { label: 'View case studies', to: '/case-studies' },
  clients: [
    {
      id: 'goodbooks',
      name: 'GoodBooks Plus',
      short: 'GBP',
      category: 'Analytics',
      logo: '/portfolio/logos/goodbooks-plus.svg',
      image: '/portfolio/goodbooks-plus/analytics-desktop.webp',
      to: '/case-studies/goodbooks-plus-analytics',
    },
    {
      id: 'medbill',
      name: 'MedBill Ultra',
      short: 'MBU',
      category: 'Healthcare',
      logo: '/portfolio/logos/medbill-ultra.svg',
      image: '/portfolio/medbill-ultra/home-desktop.webp',
      to: '/case-studies/medbill-ultra',
    },
    {
      id: 'metro',
      name: 'Metro Electric',
      short: 'ME',
      category: 'Services',
      logo: '/portfolio/logos/metro-electric.svg',
      image: '/portfolio/metro-electric/home-desktop.webp',
      to: '/case-studies/metro-electric',
    },
    {
      id: 'spaceworx',
      name: 'SpaceWorx',
      short: 'SW',
      category: 'Product',
      logo: '/portfolio/logos/spaceworx.svg',
      image: '/portfolio/spaceworx/home-desktop.webp',
      to: '/case-studies/spaceworx',
    },
    {
      id: 'mrzzm',
      name: 'MRZZM',
      short: 'MZ',
      category: 'Commerce',
      logo: '/portfolio/logos/mrzzm.svg',
      image: '/portfolio/mrzzm/home-desktop.webp',
      to: '/case-studies/mrzzm',
    },
    {
      id: 'tailorize',
      name: 'Tailorize',
      short: 'TZ',
      category: 'Fashion',
      logo: '/portfolio/logos/tailorize.svg',
      image: '/portfolio/tailorize/home-desktop.webp',
      to: '/case-studies/tailorize',
    },
    {
      id: 'servloom',
      name: 'Servloom',
      short: 'SL',
      category: 'SaaS',
      logo: '/portfolio/logos/servloom.png',
      image: '/portfolio/servloom/home-desktop.webp',
      to: '/case-studies/servloom',
    },
    // Temporarily removed with GODIVA case study — restore with status: 'published' in caseStudies.js
    // {
    //   id: 'godiva',
    //   name: 'GODIVA',
    //   short: 'GD',
    //   category: 'Retail',
    //   logo: '/portfolio/logos/godiva.svg',
    //   image: '/portfolio/godiva/home-desktop.webp',
    //   to: '/case-studies/godiva',
    // },
  ],
}
