/**
 * Converts oversized PNG/JPG assets to WebP, caps their longest edge, and
 * rewrites every reference in src/ to match.
 *
 * Encoding runs through Chromium's canvas WebP encoder (already available via
 * Playwright), so this needs no native image dependency. Alpha is preserved.
 *
 * Usage:
 *   node scripts/optimize-images.mjs --dry    # report only
 *   node scripts/optimize-images.mjs          # convert + rewrite refs
 */
import fs from 'node:fs'
import path from 'node:path'
import { chromium } from 'playwright'

const PUBLIC_DIR = 'public'
const DRY = process.argv.includes('--dry')

/** Only bother with assets big enough for the re-encode to pay for itself. */
const MIN_BYTES = 40 * 1024
/** Longest-edge cap — nothing on the site renders wider than this, even at 2x. */
const MAX_EDGE = 1920
const QUALITY = 0.9

/**
 * Left alone: vector art, already-optimised WebP, tiny brand marks, and the
 * favicon/app-icon suite — those are generated by build-favicons.mjs and the
 * manifest/`apple-touch-icon` surfaces require PNG.
 */
const SKIP = [
  /\.svg$/i,
  /\.webp$/i,
  /\/portfolio\/logos\//,
  /\/assets\/images\/icons\//,
  /^\/(favicon|apple-touch-icon|icon-)/,
  /^\/og-image\./,
]

function walk(dir, acc = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name)
    if (e.isDirectory()) walk(p, acc)
    else acc.push(p)
  }
  return acc
}

const candidates = walk(PUBLIC_DIR).filter((f) => {
  const rel = '/' + path.relative(PUBLIC_DIR, f).split(path.sep).join('/')
  if (SKIP.some((re) => re.test(rel))) return false
  if (!/\.(png|jpe?g)$/i.test(f)) return false
  return fs.statSync(f).size >= MIN_BYTES
})

console.log(`${candidates.length} candidate raster(s) >= ${MIN_BYTES / 1024}KB\n`)

const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 64, height: 64 } })
await page.goto('http://localhost:5174/robots.txt').catch(() => {})

const conversions = []
let before = 0
let after = 0

for (const file of candidates) {
  const rel = '/' + path.relative(PUBLIC_DIR, file).split(path.sep).join('/')
  const srcBytes = fs.statSync(file).size
  const b64 = fs.readFileSync(file).toString('base64')
  const mime = /\.png$/i.test(file) ? 'image/png' : 'image/jpeg'

  const out = await page.evaluate(
    async ({ b64, mime, maxEdge, quality }) => {
      const img = new Image()
      img.src = `data:${mime};base64,${b64}`
      await img.decode()
      const scale = Math.min(1, maxEdge / Math.max(img.naturalWidth, img.naturalHeight))
      const w = Math.round(img.naturalWidth * scale)
      const h = Math.round(img.naturalHeight * scale)
      const c = document.createElement('canvas')
      c.width = w
      c.height = h
      const ctx = c.getContext('2d')
      ctx.imageSmoothingQuality = 'high'
      ctx.drawImage(img, 0, 0, w, h)
      return {
        w,
        h,
        ow: img.naturalWidth,
        oh: img.naturalHeight,
        data: c.toDataURL('image/webp', quality).split(',')[1],
      }
    },
    { b64, mime, maxEdge: MAX_EDGE, quality: QUALITY },
  )

  const buf = Buffer.from(out.data, 'base64')
  const target = file.replace(/\.(png|jpe?g)$/i, '.webp')
  const relTarget = rel.replace(/\.(png|jpe?g)$/i, '.webp')

  before += srcBytes
  after += buf.byteLength
  conversions.push({ rel, relTarget, file, target, buf, srcBytes, out })

  const pct = (100 - (buf.byteLength / srcBytes) * 100).toFixed(0)
  console.log(
    `${String(Math.round(srcBytes / 1024)).padStart(6)}KB -> ${String(
      Math.round(buf.byteLength / 1024),
    ).padStart(5)}KB  (-${pct}%)  ${out.ow}x${out.oh}` +
      `${out.w !== out.ow ? ` -> ${out.w}x${out.h}` : ''}  ${rel}`,
  )
}

await browser.close()

console.log(
  `\ntotal ${(before / 1048576).toFixed(1)} MB -> ${(after / 1048576).toFixed(1)} MB ` +
    `(-${(100 - (after / before) * 100).toFixed(0)}%)`,
)

if (DRY) {
  console.log('\n--dry: nothing written')
  process.exit(0)
}

/* ---- write the WebP files, drop the originals ---- */
for (const c of conversions) {
  fs.writeFileSync(c.target, c.buf)
  if (c.target !== c.file) fs.unlinkSync(c.file)
}

/* ---- rewrite references across src/ + index.html ---- */
const sourceFiles = (function collect(dir, acc = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name)
    if (e.isDirectory()) collect(p, acc)
    else if (/\.(js|jsx|ts|tsx|css|html)$/.test(e.name)) acc.push(p)
  }
  return acc
})('src').concat(['index.html'])

const renames = new Map(conversions.map((c) => [c.rel, c.relTarget]))
let touched = 0

for (const file of sourceFiles) {
  const text = fs.readFileSync(file, 'utf8')
  let next = text
  for (const [from, to] of renames) {
    if (next.includes(from)) next = next.split(from).join(to)
  }
  if (next !== text) {
    fs.writeFileSync(file, next)
    touched += 1
    console.log(`updated refs in ${file}`)
  }
}

console.log(`\nconverted ${conversions.length} file(s), updated ${touched} source file(s)`)
